import {GOLD, SPECIAL, PlayerConfig} from '../src/models';

const players: PlayerConfig[] = [
    {
        name: 'José María Giménez',
        quality: GOLD,
        rating: 84,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 2900,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 3000,
            maxIterations: 150,
            playersToBuy: 5,
        },
        sell: {price: 100},
    },
    {
        name: 'Carvajal',
        quality: GOLD,
        rating: 84,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 3000,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 3000,
            maxIterations: 150,
            playersToBuy: 5,
        },
        sell: {price: 100},
    },
    {
        name: 'Koke',
        quality: GOLD,
        rating: 85,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 3000,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 10000,
            maxIterations: 150,
            playersToBuy: 5,
        },
        sell: {price: 100},
    },
    {
        name: 'Marco Asensio',
        quality: GOLD,
        rating: 85,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 9800,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 10000,
            maxIterations: 150,
            playersToBuy: 5,
        },
        sell: {price: 100},
    },
    {
        name: 'Miranda',
        quality: GOLD,
        rating: 85,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 10000,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 10000,
            maxIterations: 150,
            playersToBuy: 5,
        },
        sell: {price: 100},
    },
    {
        name: 'Saúl',
        quality: GOLD,
        rating: 85,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 10000,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 10000,
            maxIterations: 150,
            playersToBuy: 5,
        },
        sell: {price: 100},
    },
    {
        name: 'Pizzi',
        quality: SPECIAL,
        rating: 85,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 350,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 24000,
            maxIterations: 150,
            playersToBuy: 5,
        },
        sell: {price: 100},
    },
    //
    {
        name: 'Emmanuel Adebayor',
        quality: GOLD,
        rating: 79,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 350,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 0,
            maxIterations: 350,
            playersToBuy: 1,
        },
        sell: {price: 1200},
    },
    {
        name: 'Igor Akinfeev',
        quality: SPECIAL,
        rating: 81,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 350,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 0,
            maxIterations: 350,
            playersToBuy: 1,
        },
        sell: {price: 1500},
    },
    {
        name: 'Sébastien Corchia',
        quality: GOLD,
        rating: 75,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 350,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 0,
            maxIterations: 350,
            playersToBuy: 1,
        },
        sell: {price: 850},
    },
    {
        name: 'Samuel Gigot',
        quality: GOLD,
        rating: 76,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 350,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 0,
            maxIterations: 350,
            playersToBuy: 1,
        },
        sell: {price: 500000},
    },
    {
        name: 'Soares',
        quality: GOLD,
        rating: 79,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 700,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 0,
            maxIterations: 700,
            playersToBuy: 1,
        },
        sell: {price: 500000},
    },
    {
        name: 'Jorge Meré',
        quality: GOLD,
        rating: 77,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 350,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 0,
            maxIterations: 350,
            playersToBuy: 1,
        },
        sell: {price: 500000},
    },
];

export default players;
