import {GOLD, SPECIAL, PlayerConfig} from '../src/models';

const players: PlayerConfig[] = [
    {
        name: 'José María Giménez',
        quality: GOLD,
        rating: 84,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 2900,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 240,
        },
        buyNow: {
            maxBuyNowPrice: 3000,
            maxIterations: 150,
            playersToBuy: 5,
        },
    },
    {
        name: 'Carvajal',
        quality: GOLD,
        rating: 84,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 3000,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 120,
        },
        buyNow: {
            maxBuyNowPrice: 3000,
            maxIterations: 150,
            playersToBuy: 5,
        },
    },
    {
        name: 'Koke',
        quality: GOLD,
        rating: 85,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 3000,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 10000,
            maxIterations: 150,
            playersToBuy: 5,
        },
    },
    {
        name: 'Marco Asensio',
        quality: GOLD,
        rating: 85,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 9800,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 10000,
            maxIterations: 150,
            playersToBuy: 5,
        },
    },
    {
        name: 'Miranda',
        quality: GOLD,
        rating: 85,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 10000,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 10500,
            maxIterations: 150,
            playersToBuy: 5,
        },
    },
    {
        name: 'Saúl',
        quality: GOLD,
        rating: 85,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 10000,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 10000,
            maxIterations: 150,
            playersToBuy: 5,
        },
    },
    {
        name: 'Pizzi',
        quality: SPECIAL,
        rating: 85,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 350,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 24000,
            maxIterations: 150,
            playersToBuy: 5,
        },
    },
    {
        name: 'Lucas Hernández',
        quality: GOLD,
        rating: 82,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 3500,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 3500,
            maxIterations: 350,
            playersToBuy: 4,
        },
        sell: {price: 6000},
    },
    {
        name: 'Rodrigo',
        quality: GOLD,
        rating: 84,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 3000,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 3000,
            maxIterations: 150,
            playersToBuy: 5,
        },
    },
    {
        name: 'Marco Verratti',
        quality: GOLD,
        rating: 86,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 12000,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 16000,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 16000,
            maxIterations: 150,
            playersToBuy: 2,
        },
    },
    {
        name: 'Keylor Navas',
        quality: GOLD,
        rating: 87,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 12000,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 22000,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 22000,
            maxIterations: 150,
            playersToBuy: 2,
        },
    },
    {
        name: 'Ciro Immobile',
        quality: GOLD,
        rating: 87,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 12000,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 22000,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 22000,
            maxIterations: 150,
            playersToBuy: 2,
        },
    },
    {
        name: 'Nicolás Otamendi',
        quality: GOLD,
        rating: 86,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 12000,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 120,
        },
        buyNow: {
            maxBuyNowPrice: 16500,
            maxIterations: 150,
            playersToBuy: 2,
        },
    },
    {
        name: 'Isco',
        quality: GOLD,
        rating: 89,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 12000,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 22000,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 42500,
            maxIterations: 150,
            playersToBuy: 1,
        },
    },
    {
        name: 'Felipe Anderson',
        quality: GOLD,
        rating: 84,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 12000,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 22000,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 4000,
            maxIterations: 150,
            playersToBuy: 1,
        },
    },
    {
        name: 'Takashi Inui',
        quality: SPECIAL,
        rating: 80,
        buyNow: {
            maxBuyNowPrice: 13750,
            maxIterations: 175,
            playersToBuy: 2,
        },
    },
    {
        name: 'Alderweireld',
        quality: GOLD,
        rating: 85,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 10000,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 120,
        },
        buyNow: {
            maxBuyNowPrice: 15000,
            maxIterations: 150,
            playersToBuy: 2,
        },
        sell: {price: 1200},
    },
    {
        name: 'Cesc Fàbregas',
        quality: GOLD,
        rating: 84,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 3000,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 120,
        },
        buyNow: {
            maxBuyNowPrice: 3000,
            maxIterations: 150,
            playersToBuy: 6,
        },
        sell: {price: 1200},
    },
    {
        name: 'Roberto Soriano',
        quality: GOLD,
        rating: 78,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 700,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 700,
            maxIterations: 150,
            playersToBuy: 1,
        },
        sell: {price: 1300},
    },
    {
        name: 'Jordi Alba',
        quality: GOLD,
        rating: 87,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 700,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 27000,
            maxIterations: 350,
            playersToBuy: 5,
        },
        sell: {price: 300000},
    },
    {
        name: 'Iago Falqué',
        quality: GOLD,
        rating: 80,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 350,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 350,
            maxIterations: 350,
            playersToBuy: 1,
        },
        sell: {price: 700},
    },
    {
        name: 'Raúl Albiol',
        quality: GOLD,
        rating: 84,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 4500,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 4500,
            maxIterations: 350,
            playersToBuy: 4,
        },
        sell: {price: 7800},
    },
    {
        name: 'Saúl',
        quality: SPECIAL,
        rating: 86,
        buyNow: {
            maxBuyNowPrice: 25000, // 33500
            maxIterations: 150,
            playersToBuy: 1,
        },
        sell: {price: 45000},
    },
    {
        name: 'Williams',
        quality: SPECIAL,
        rating: 84,
        buyNow: {
            maxBuyNowPrice: 61000, // 68000
            maxIterations: 150,
            playersToBuy: 1,
        },
        sell: {price: 88000},
    },
    {
        name: 'Rodrigo',
        quality: SPECIAL,
        rating: 86,
        buyNow: {
            minBuyNowPrice: 40000,
            maxBuyNowPrice: 57000, // 60000
            maxIterations: 150,
            playersToBuy: 1,
        },
        sell: {price: 88000},
    },
    {
        name: 'Sergio Ramos',
        quality: GOLD,
        rating: 91,
        buyNow: {
            maxBuyNowPrice: 180000, // 200000
            maxIterations: 350,
            playersToBuy: 1,
        },
        sell: {price: 300000},
    },
    {
        name: 'Oscar',
        quality: GOLD,
        rating: 81,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 350,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        sell: {price: 900},
    },
    {
        name: 'Christoph Kramer',
        quality: GOLD,
        rating: 81,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 350,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 4600,
        },
        sell: {price: 900},
    },
    {
        name: 'Ángel Correa',
        quality: GOLD,
        rating: 80,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 700,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 1200,
        },
        sell: {price: 2000},
    },
    {
        name: 'Clément Lenglet',
        quality: GOLD,
        rating: 82,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 700,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 6600,
        },
        sell: {price: 3000},
    },
    {
        name: 'Jeison Murillo',
        quality: GOLD,
        rating: 81,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 700,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 6600,
        },
        sell: {price: 1000},
    },
    {
        name: 'João Cancelo',
        quality: GOLD,
        rating: 81,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 700,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 1800,
        },
        sell: {price: 3000},
    },
    {
        name: 'Marcelo',
        quality: GOLD,
        rating: 81,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 650,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 1800,
        },
        sell: {price: 1000},
    },
    {
        name: 'Igor Akinfeev',
        quality: SPECIAL,
        rating: 81,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 350,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 0,
            maxIterations: 350,
            playersToBuy: 1,
        },
        sell: {price: 1500},
    },
    {
        name: 'Raúl García',
        quality: GOLD,
        rating: 81,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 700,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 700,
            maxIterations: 350,
            playersToBuy: 4,
        },
        sell: {price: 1200},
    },
];

export default players;
