import {GOLD, SPECIAL, PlayerConfig} from '../src/models';

const players: PlayerConfig[] = [
    {
        name: 'José María Giménez',
        quality: GOLD,
        rating: 84,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 2900,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 3000,
            maxIterations: 150,
            playersToBuy: 5,
        },
        sell: {price: 100},
    },
    {
        name: 'Carvajal',
        quality: GOLD,
        rating: 84,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 3000,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 3000,
            maxIterations: 150,
            playersToBuy: 5,
        },
        sell: {price: 100},
    },
    {
        name: 'Koke',
        quality: GOLD,
        rating: 85,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 3000,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 10000,
            maxIterations: 150,
            playersToBuy: 5,
        },
        sell: {price: 100},
    },
    {
        name: 'Marco Asensio',
        quality: GOLD,
        rating: 85,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 9800,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 10000,
            maxIterations: 150,
            playersToBuy: 5,
        },
        sell: {price: 100},
    },
    {
        name: 'Miranda',
        quality: GOLD,
        rating: 85,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 10000,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 10000,
            maxIterations: 150,
            playersToBuy: 5,
        },
        sell: {price: 100},
    },
    {
        name: 'Saúl',
        quality: GOLD,
        rating: 85,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 10000,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 10000,
            maxIterations: 150,
            playersToBuy: 5,
        },
        sell: {price: 100},
    },
    {
        name: 'Pizzi',
        quality: SPECIAL,
        rating: 85,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 350,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 24000,
            maxIterations: 150,
            playersToBuy: 5,
        },
        sell: {price: 100},
    },
    {
        name: 'Emmanuel Adebayor',
        quality: GOLD,
        rating: 79,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 350,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 0,
            maxIterations: 350,
            playersToBuy: 1,
        },
        sell: {price: 1100},
    },
    {
        name: 'Igor Akinfeev',
        quality: SPECIAL,
        rating: 81,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 350,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 0,
            maxIterations: 350,
            playersToBuy: 1,
        },
        sell: {price: 1500},
    },
    {
        name: 'Sébastien Corchia',
        quality: GOLD,
        rating: 75,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 350,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 0,
            maxIterations: 350,
            playersToBuy: 1,
        },
        sell: {price: 850},
    },
    {
        name: 'Samuel Gigot',
        quality: GOLD,
        rating: 76,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 350,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 0,
            maxIterations: 350,
            playersToBuy: 1,
        },
        sell: {price: 500000},
    },
    {
        name: 'Soares',
        quality: GOLD,
        rating: 79,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 700,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 0,
            maxIterations: 700,
            playersToBuy: 1,
        },
        sell: {price: 500000},
    },
    {
        name: 'Jorge Meré',
        quality: GOLD,
        rating: 77,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 350,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 0,
            maxIterations: 350,
            playersToBuy: 1,
        },
        sell: {price: 500000},
    },
    {
        name: 'Lucas Hernández',
        quality: GOLD,
        rating: 82,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 3500,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 3500,
            maxIterations: 350,
            playersToBuy: 4,
        },
        sell: {price: 6000},
    },
    {
        name: 'Raúl García',
        quality: GOLD,
        rating: 81,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 700,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 700,
            maxIterations: 350,
            playersToBuy: 4,
        },
        sell: {price: 1200},
    },
    {
        name: 'Rodrigo',
        quality: GOLD,
        rating: 84,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 3000,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 3000,
            maxIterations: 150,
            playersToBuy: 5,
        },
        sell: {price: 100},
    },
    {
        name: 'Marco Verratti',
        quality: GOLD,
        rating: 86,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 12000,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 16000,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 16000,
            maxIterations: 150,
            playersToBuy: 2,
        },
        sell: {price: 100},
    },
    {
        name: 'Keylor Navas',
        quality: GOLD,
        rating: 87,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 12000,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 22000,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 22000,
            maxIterations: 150,
            playersToBuy: 2,
        },
        sell: {price: 100},
    },
    {
        name: 'Ciro Immobile',
        quality: GOLD,
        rating: 87,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 12000,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 22000,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 22000,
            maxIterations: 150,
            playersToBuy: 2,
        },
        sell: {price: 100},
    },
    {
        name: 'Nicolás Otamendi',
        quality: GOLD,
        rating: 86,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 12000,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 22000,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 16500,
            maxIterations: 150,
            playersToBuy: 2,
        },
        sell: {price: 100},
    },
    {
        name: 'Isco',
        quality: GOLD,
        rating: 89,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 12000,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 22000,
            maxExpirationTime: 3600,
        },
        buyNow: {
            maxBuyNowPrice: 40000,
            maxIterations: 150,
            playersToBuy: 1,
        },
        sell: {price: 100},
    },
    {
        name: 'Morgan Sanson',
        quality: GOLD,
        rating: 80,
        bid: {
            minBidPrice: 0,
            maxBidPrice: 350,
            minBuyNowPrice: 0,
            maxBuyNowPrice: 0,
            maxExpirationTime: 8600,
        },
        buyNow: {
            maxBuyNowPrice: 350,
            maxIterations: 150,
            playersToBuy: 1,
        },
        sell: {price: 1200},
    },
];

export default players;
